# web/Dockerfile.dev
FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache bash libc6-compat

ENV CI=true NODE_ENV=development

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm","run","dev"]